version: "3.7"

services:
  postgres:
    build:
      context: ./docker/postgresql
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: "didinele"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "didinele"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U didinele"]
      interval: 10s
      timeout: 5s

  auth:
    build:
      context: ./
      dockerfile: ./docker/auth/Dockerfile
    environment:
      DISCORD_SCOPES: "identify,email"
    restart: unless-stopped
    expose:
      - "3000"

  personal:
    build:
      context: ./
      dockerfile: ./docker/personal/Dockerfile
    restart: unless-stopped
    expose:
      - "4200"

volumes:
  postgres-data:
    name: "didinele.me-postgres-data"
